blank_issues_enabled: false
contact_links:
  - name: New Haven Roleplay Issue Tracker
    url: hhttps://github.com/newhaven-rp/Issue-Tracker
    about: If you have any suggestions regarding any server assets in relation to Cars, Clothing, MLO's, etc, make a suggestion here.
  - name: New Haven Roleplay Discord
    url: https://discord.gg/newhaven-rp
    about: Come join us to enjoy your New Haven! 